### PR TITLE
Issue186 correct class path

### LINKED ISSUE #185: Update Maven link
The link for downloading Maven (http://apache.mirrors.lucidnetworks.net/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz) is no longer valid. This issue is to update the link to a valid one as shown in https://maven.apache.org/download.cgi.

### PR DESCRIPTION
**Pull request by JayHuLBL**
This closes #185, #186.

- [x] updated download link of Maven. This addressed issue #185.
- [x] updated the CDL classes as blocks like `CDL.Continuous.LimPID` and `CDL.Continuous.Gain` are no longer valid.
- [x] corrected a bug when exporting HTML in modelica mode.
- [x] updated reference results

### CODE REVIEW

**Comment by JayHuLBL** [comment]
@anandkp92 Would you please check if you see the issues #185 and #186, and if yes, see if this PR fix that?

**Comment by anandkp92** [comment]
Hi @JayHuLBL 

The maven path seems to work! However, I encountered an issue where I had both 3.6.3 and 3.8.5 maven versions and there were some errors. Maybe we can include a "rm -r apache_maven" before downloading and extracting? 

Regarding the other changes. I see that you have fixed some updates to CDL and also regenerated the reference results. But when I run `make test`, I still run into failures. 

```
...
  util
    getModelicaFileName()
      ✓ must be equal
    getModelicaFileName() with full name
      ✓ must be equal


  17 passing (2m)

(node:65185) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:65185) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:65185) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:65185) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:65185) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:65185) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:65185) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:65185) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:65185) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:65185) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:65185) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:65185) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:65185) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:65185) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:65185) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:65185) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:65185) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:65185) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:65185) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
(node:65185) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
(node:65185) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
(node:65185) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
(node:65185) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
(node:65185) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:65185) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
(node:65185) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:65185) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:65185) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
(node:65185) Warning: Accessing non-existent property 'which' of module exports inside circular dependency
standard: Use JavaScript Standard Style (https://standardjs.com)
standard: Run `standard --fix` to automatically fix some problems.
  /Users/akprakash/Programming/modelica/modelica-json/2app.js:75:18: Extra semicolon.
  /Users/akprakash/Programming/modelica/modelica-json/2app.js:76:1: 'outputs' is not defined.
  /Users/akprakash/Programming/modelica/modelica-json/2app.js:76:29: Strings must use singlequote.
  /Users/akprakash/Programming/modelica/modelica-json/2app.js:78:1: 'rawJsonData' is not defined.
  /Users/akprakash/Programming/modelica/modelica-json/2app.js:80:1: 'outputs' is not defined.
  /Users/akprakash/Programming/modelica/modelica-json/2app.js:80:25: Missing space before function parentheses.
  /Users/akprakash/Programming/modelica/modelica-json/2app.js:84:5: Closing curly brace does not appear on the same line as the subsequent block.
  /Users/akprakash/Programming/modelica/modelica-json/2app.js:87:5: Closing curly brace does not appear on the same line as the subsequent block.
  /Users/akprakash/Programming/modelica/modelica-json/2app.js:90:5: Closing curly brace does not appear on the same line as the subsequent block.
  /Users/akprakash/Programming/modelica/modelica-json/2app.js:93:74: 'rawJsonData' is not defined.
  /Users/akprakash/Programming/modelica/modelica-json/2app.js:95:3: Closing curly brace does not appear on the same line as the subsequent block.
  /Users/akprakash/Programming/modelica/modelica-json/2app.js:98:30: 'rawJsonData' is not defined.
  /Users/akprakash/Programming/modelica/modelica-json/2app.js:100:3: Extra semicolon.
  /Users/akprakash/Programming/modelica/modelica-json/2app.js:105:21: Extra semicolon.
  /Users/akprakash/Programming/modelica/modelica-json/2app.js:106:1: 'outputs' is not defined.
  /Users/akprakash/Programming/modelica/modelica-json/2app.js:106:25: Missing space before function parentheses.
  /Users/akprakash/Programming/modelica/modelica-json/2app.js:108:3: Extra semicolon.
  /Users/akprakash/Programming/modelica/modelica-json/2app.js:113:1: 'outputs' is not defined.
  /Users/akprakash/Programming/modelica/modelica-json/2app.js:113:25: Missing space before function parentheses.
  /Users/akprakash/Programming/modelica/modelica-json/2app.js:117:3: Extra semicolon.
  /Users/akprakash/Programming/modelica/modelica-json/jsParser/main.js:4:39: Extra semicolon.
  /Users/akprakash/Programming/modelica/modelica-json/jsParser/main.js:5:62: Extra semicolon.
  /Users/akprakash/Programming/modelica/modelica-json/jsParser/main.js:6:60: Extra semicolon.
  /Users/akprakash/Programming/modelica/modelica-json/jsParser/main.js:7:7: Identifier 'stored_definitionVisitor' is not in camel case.
  /Users/akprakash/Programming/modelica/modelica-json/jsParser/main.js:7:71: Extra semicolon.
  /Users/akprakash/Programming/modelica/modelica-json/jsParser/main.js:11:49: Extra semicolon.
  /Users/akprakash/Programming/modelica/modelica-json/jsParser/main.js:13:57: Extra semicolon.
  /Users/akprakash/Programming/modelica/modelica-json/jsParser/main.js:14:33: A constructor name should not start with a lowercase letter.
  /Users/akprakash/Programming/modelica/modelica-json/jsParser/main.js:14:59: Extra semicolon.
  /Users/akprakash/Programming/modelica/modelica-json/jsParser/main.js:15:62: Extra semicolon.
  /Users/akprakash/Programming/modelica/modelica-json/jsParser/main.js:16:35: A constructor name should not start with a lowercase letter.
  /Users/akprakash/Programming/modelica/modelica-json/jsParser/main.js:16:68: Extra semicolon.
  /Users/akprakash/Programming/modelica/modelica-json/jsParser/main.js:17:46: A constructor name should not start with a lowercase letter.
  /Users/akprakash/Programming/modelica/modelica-json/jsParser/main.js:17:72: Extra semicolon.
  /Users/akprakash/Programming/modelica/modelica-json/jsParser/main.js:19:42: Extra semicolon.
  /Users/akprakash/Programming/modelica/modelica-json/jsParser/main.js:20:1: Too many blank lines at the end of file. Max of 0 allowed.
  /Users/akprakash/Programming/modelica/modelica-json/jsParser/stored_definitionVisitor.js:1:80: Extra semicolon.
  /Users/akprakash/Programming/modelica/modelica-json/jsParser/stored_definitionVisitor.js:2:7: Identifier 'stored_definition' is not in camel case.
  /Users/akprakash/Programming/modelica/modelica-json/jsParser/stored_definitionVisitor.js:2:64: Extra semicolon.
  /Users/akprakash/Programming/modelica/modelica-json/jsParser/stored_definitionVisitor.js:3:7: 'nameVisitor' is assigned a value but never used.
  /Users/akprakash/Programming/modelica/modelica-json/jsParser/stored_definitionVisitor.js:3:45: Extra semicolon.
  /Users/akprakash/Programming/modelica/modelica-json/jsParser/stored_definitionVisitor.js:5:7: Identifier 'stored_definitionVisitor' is not in camel case.
  /Users/akprakash/Programming/modelica/modelica-json/jsParser/stored_definitionVisitor.js:6:5: Expected indentation of 2 spaces but found 4.
  /Users/akprakash/Programming/modelica/modelica-json/jsParser/stored_definitionVisitor.js:6:16: Missing space before function parentheses.
  /Users/akprakash/Programming/modelica/modelica-json/jsParser/stored_definitionVisitor.js:7:9: Expected indentation of 6 spaces but found 8.
  /Users/akprakash/Programming/modelica/modelica-json/jsParser/stored_definitionVisitor.js:7:35: Extra semicolon.
  /Users/akprakash/Programming/modelica/modelica-json/jsParser/stored_definitionVisitor.js:8:9: Expected indentation of 6 spaces but found 8.
  /Users/akprakash/Programming/modelica/modelica-json/jsParser/stored_definitionVisitor.js:8:20: Extra semicolon.
  /Users/akprakash/Programming/modelica/modelica-json/jsParser/stored_definitionVisitor.js:10:5: Expected indentation of 2 spaces but found 4.
  /Users/akprakash/Programming/modelica/modelica-json/jsParser/stored_definitionVisitor.js:10:5: Identifier 'visitStored_definition' is not in camel case.
  /Users/akprakash/Programming/modelica/modelica-json/jsParser/stored_definitionVisitor.js:10:27: Missing space before function parentheses.
  /Users/akprakash/Programming/modelica/modelica-json/jsParser/stored_definitionVisitor.js:11:9: Expected indentation of 6 spaces but found 8.
  /Users/akprakash/Programming/modelica/modelica-json/jsParser/stored_definitionVisitor.js:12:13: Expected indentation of 10 spaces but found 12.
  /Users/akprakash/Programming/modelica/modelica-json/jsParser/stored_definitionVisitor.js:13:11: Extra semicolon.
  /Users/akprakash/Programming/modelica/modelica-json/jsParser/stored_definitionVisitor.js:14:1: Trailing spaces not allowed.
  /Users/akprakash/Programming/modelica/modelica-json/jsParser/stored_definitionVisitor.js:14:1: More than 1 blank line not allowed.
  /Users/akprakash/Programming/modelica/modelica-json/jsParser/stored_definitionVisitor.js:16:9: Expected indentation of 6 spaces but found 8.
  /Users/akprakash/Programming/modelica/modelica-json/jsParser/stored_definitionVisitor.js:16:67: Extra semicolon.
  /Users/akprakash/Programming/modelica/modelica-json/jsParser/stored_definitionVisitor.js:20:78: Extra semicolon.
  /Users/akprakash/Programming/modelica/modelica-json/jsParser/stored_definitionVisitor.js:22:36: Identifier 'stored_definitionVisitor' is not in camel case.
  /Users/akprakash/Programming/modelica/modelica-json/jsParser/stored_definitionVisitor.js:22:60: Extra semicolon.
  /Users/akprakash/Programming/modelica/modelica-json/jsParser/stored_definitionVisitor.js:23:61: Extra semicolon.
  /Users/akprakash/Programming/modelica/modelica-json/jsParser/stored_definitionVisitor.js:23:62: Newline required at end of file but not found.
```

Not sure if this is an issue with my local installation.

**Comment by JayHuLBL** [comment]
@anandkp92
The warnings you reported would be caused by the inside circular dependency, such like in `lib/util.js` requiring `lib/parser.js`, while `lib/parser.js` requiring `lib/util.js`. 
Regarding the errors like:
`  /Users/akprakash/Programming/modelica/modelica-json/jsParser/main.js:4:39: Extra semicolon.`, is it something related to your work on converting Java script to JavaScript script? I don't record we have `main.js` script, but do have `Main.java`.

**Comment by JayHuLBL** [comment]
This PR will be merged. The warnings will be addressed in separated issue #188.

**Comment by anandkp92** [comment]
So jsParser/main.js is a local file on my computer that is part of another issue. When we run ``make test`` it runs all the js scripts in the folder, including my in-progress files. So I tried running ``make test`` with a fresh clone of the repository and everything worked fine!

**Pull request merged**
