### PR TITLE
Issue106 rep nul

### LINKED ISSUE #106: TypeError: Cannot read property 'replace' of null
The following commands fail
```bash
git clone git@github.com:lbl-srg/modelica-buildings.git
cd modelica-buildings
git checkout 067b6e41640a5813fad108b61196402ff5d82da8
cd -

git clone git@github.com:lbl-srg/modelica-json.git
cd modelica-json/
make install
make compile
node app.js -f ../modelica-buildings/Buildings/Examples/Tutorial/CDL -o docx -m modelica -d out
```
The error message is
```bash
warn:    Instance "vol" has no comment. Check Buildings.Examples.Tutorial.CDL.BaseClasses.PartialOpenLoop
warn:    Instance "spl2" has no comment. Check Buildings.Examples.Tutorial.CDL.BaseClasses.PartialOpenLoop
warn:    Instance "weaBus" has no comment. Check Buildings.Examples.Tutorial.CDL.BaseClasses.PartialOpenLoop
warn:    Instance "conEquSta" has no comment. Check Buildings.Examples.Tutorial.CDL.Controls.Validation.EquipmentOnOff
warn:    Instance "conRadSup" has no comment. Check Buildings.Examples.Tutorial.CDL.Controls.Validation.RadiatorSupply
warn:    Instance "conSysSta" has no comment. Check Buildings.Examples.Tutorial.CDL.Controls.Validation.SystemOnOff
/home/mwetter/test/modelica-json/lib/jsonquery.js:118
    'comment': getComment(model).replace(/"/g, ''),
                                ^

TypeError: Cannot read property 'replace' of null
    at Object.simplifyModelicaJSON (/home/mwetter/test/modelica-json/lib/jsonquery.js:118:33)
    at getJsons (/home/mwetter/test/modelica-json/lib/parser.js:180:19)
    at Object.getJSON (/home/mwetter/test/modelica-json/lib/parser.js:147:21)
    at Object.<anonymous> (/home/mwetter/test/modelica-json/app.js:76:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

### PR DESCRIPTION
**Pull request by JayHuLBL**
This closes #106.

- [x] added warning when there is no class comment
- [x] added warning when cannot find connector instance in current model

### CODE REVIEW

**Comment by JayHuLBL** [comment]
@mwetter Run following command: 
```
node app.js -f ../modelica-buildings/Buildings/Examples/Tutorial/CDL -o docx -m modelica -d out
```
can successfully generate docx file for the package. However, the parser would try to find the all the connector's source but due to the extended class, it cannot find it in current class. There will be warning to flag that.

**Comment by JayHuLBL** [comment]
@mwetter It's ready for your review.

**Comment by mwetter** [comment]
@JayHuLBL : What do the warnings mean? Will they be fixed through another issue (which one?).

For example, I get
```
arn:    Buildings.Examples.Tutorial.CDL.Controls.Validation has no class comment.
warn:    Buildings.Examples.Tutorial.CDL.Controls has no info section, or the info section is misplaced.
warn:    Did not find instance for connector pumRad in Buildings.Examples.Tutorial.CDL.System1, may find it in the base class.
warn:    Did not find instance for connector boi in Buildings.Examples.Tutorial.CDL.System1, may find it in the base class.
```
but the Modelica model seems to be valid. Does the "may find it in the base class" mean anything? Was it found or is this something the user needs to know and fix?


The formatting needs work: I think the Type should be on its own line as currently it uses more than half the width, and the other columns are squeezed too much. Also, the figures are too wide. Maybe this should be done through a new issue so it does not block this one.

**Comment by JayHuLBL** [comment]
@mwetter 

```
warn:    Buildings.Examples.Tutorial.CDL.Controls.Validation has no class comment.
```
It captures that `Buildings.Examples.Tutorial.CDL.Controls.Validation.package.mo` does not have class comment:
```
within Buildings.Examples.Tutorial.CDL.Controls;
package Validation  *****(comment is missing)*****
  extends Modelica.Icons.ExamplesPackage;

  annotation (Documentation(info="<html>
```
---
```
warn:    Buildings.Examples.Tutorial.CDL.Controls has no info section, or the info section is misplaced.
```
means that `Buildings.Examples.Tutorial.CDL.Controls.package.mo` does not have info section:
```
within Buildings.Examples.Tutorial.CDL;
package Controls "Package with the controllers used in the tutorial"
extends Modelica.Icons.VariantsPackage;
end Controls;
```
---
```
warn:    Did not find instance for connector pumRad in Buildings.Examples.Tutorial.CDL.System1, may find it in the base class.
warn:    Did not find instance for connector boi in Buildings.Examples.Tutorial.CDL.System1, may find it in the base class.
```
These warnings flag that the connector cannot find in current class and they are inherited from base classes. User do not need to fix anything. I think it might be unnecessary to flag them. 
---
For the html formatting, I think we can revise it in another issue. Thanks for the suggestions.

**Comment by mwetter** [comment]
@JayHuLBL : If the warnings are not needed please remove them or use `logger.debug` instead of a warning.

**Comment by JayHuLBL** [comment]
@mwetter I have removed the warnings. Could we merge this PR? 
I have addressed issue #148 and #149, and will make PRs after this PR merged.

**Pull request merged**
